apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-route
  namespace: talha-rasool-dev
spec:
  to:
    kind: Service
    name: flask-service
  port:
    targetPort: 80
  tls:
    termination: edge
