apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: rasooltalha/flask-postgres:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_HOST
              value: postgres # Service name
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
