name: Dev Deploy to OpenShift

on:
  push:
    branches: [dev] # Triggers on pushes to dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-postgres:dev .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-postgres:dev

      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Set KUBECONFIG environment
        run: echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Create Secret from Template
        run: |
          envsubst < k8s/postgres-secret.yaml > k8s/postgres-secret-rendered.yaml
          kubectl apply -f k8s/postgres-secret-rendered.yaml
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Apply Kubernetes manifests
        run: |

          kubectl config set-context --current --namespace=
          for file in k8s/*.yaml; do
            kubectl apply -f $file
          done
