name: Dev Deploy to OpenShift

on:
  push:
    branches: [dev] # Triggers on pushes to dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-postgres:dev .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-postgres:dev

      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Set KUBECONFIG environment
        run: echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Create Namespace (if not exists)
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Create PostgreSQL Secret in Kubernetes
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \

            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --namespace=flask-demo-dev

      - name: Apply Kubernetes manifests
        run: |

          kubectl config set-context --current --namespace=flask-demo-dev
          for file in k8s/*.yaml; do
            kubectl apply -f $file
          done
